apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: probe-demo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

    # Liveness Probe
    livenessProbe:
      httpGet:
        path: /
        port: 80

    # Readiness Probe
    readinessProbe:
      httpGet:
        path: /
        port: 80
