# here we r creating a custom resource definition

kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata: 
  name: devopsbatches.trainwithshubham.com
spec: 
  group: trainwithshubham.com
  names: 
    plural: devopsbatches
    singular: devopsbatch
    kind: DevOpsBatch
    shortNames: 
      - junoon
      - batches
      - tws
  scope: Namespaced #namespace k aandar scoped ho skta hai
  versions: 
  - name: v1
    served: true
    storage: true
    schema: 
      openAPIV3Schema: 
        type: object
        properties: 
          spec: 
            type: object
            properties: 
              name: 
                type: string
                description: 'This is the name of the  DevOpsBatch'
              duration: 
                type: string
                description: 'This is the duration of DevOpsBatch'
              mode: 
                type: string
                description: 'This is the mode of batch [live]'
              platform: 
                type: string
                description: 'This is the platform of the batch'
