apiVersion: v1
kind: Pod
metadata:
  name: init-test

spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh","-c","echo 'Initalization started....'; sleep 10; echo 'Initalization completed..'" ]


  containers:
  - name: main-container
    image: busybox:latest
    command: ["sh", "-c", "echo 'Main container started....'; sleep 3600"]
