# Stateful yml
kind:  Stateful
apiVersion: apps/v1
metadata: 
  name: mysql-stateful
  namespace: mysql

spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
      - name: mysql
        image: mysql:8.0
        ports: 
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD     # jake secrets file dekh
          valueFrom: 
            configMapKeyRef: 
              name: mysql-secrets-map
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE  
          valueFrom: 
            configMapKeyRef: # jake config file dekh
              name: mysql-config-map
              key: MYSQL_DATABASE

        volumeMounts: 
        - name: mysql-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates: 
  - metadata: 
      name: mysql-data
    spec: 
      accessModes: ['ReadWriteOnce']
      resources: 
        requests: 
          storage: 1Gi
